# Generated by Django 5.1.1 on 2024-10-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Придумайте уникальный никнейм",
                max_length=16,
                unique=True,
                verbose_name="никнейм",
            ),
        ),
    ]
