services:
  backend:
    build: ./justhink_server
    volumes:
      - static_files:/usr/src/app/static
      - media_files:/usr/src/app/media
      - /tmp:/tmp
    depends_on:
      - redis
    env_file:
      - .env

  frontend:
    build: ./justhink_client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000

  nginx:
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - static_files:/usr/src/app/static
      - media_files:/usr/src/app/media
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:80

  redis:
    image: redis:alpine
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

volumes:
  static_files:
  media_files:
