# Generated by Django 5.1.1 on 2024-10-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("RU", "Russian"),
                            ("EN", "English"),
                            ("DE", "German"),
                        ],
                        default="RU",
                        max_length=2,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="name",
                        help_text="Укажите название колоды",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_on", null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "колода",
                "verbose_name_plural": "колоды",
            },
        ),
    ]
