# Generated by Django 5.1.1 on 2024-10-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_public",
            field=models.BooleanField(
                db_column="is_public",
                default=True,
                verbose_name="публичная колода",
            ),
        ),
    ]
