[tool.ruff]
line-length = 79
src = ["justhink"]
target-version = "py312"

[tool.ruff.lint]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true