# Generated by Django 5.1.1 on 2024-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        db_column="text",
                        help_text="Введите понятие для карты",
                        max_length=300,
                        verbose_name="текст",
                    ),
                ),
            ],
            options={
                "verbose_name": "карта",
                "verbose_name_plural": "карты",
            },
        ),
    ]
