# Generated by Django 5.1.1 on 2024-10-03 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cards", "0001_initial"),
        ("deck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="deck.deck",
            ),
        ),
    ]
