name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push, pull_request]
jobs:
  run_unittests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies 
        run: |
          python3 -m pip install --upgrade pip
          pip install -r justhink_server/requirements/test.txt
      - name: Run Tests
        run: |
          echo DJANGO_SECRET_KEY = django-insecure-dummy-secret > justhink_server/.env
          cd justhink_server/justhink
          python3 manage.py test